### PR TITLE
"Convert" tools/InitD.java into a fragment; include it into headers

### PR DESCRIPTION
**Pull request by Rdlgrmpf**
Credit for the icons go to Daniel (https://github.com/speedydaniel)
To fully work,
https://github.com/AOKP/vendor_aokp/commit/c0dee2a57d6f5d85a275c8959f33975d7d3ab7a6 and
https://github.com/AOKP/vendor_aokp/commit/4f6237033c51a5f45a9b2152706341cb9828ca53
need to be reverted.

### CODE REVIEW

**Comment by LorDClockaN** [comment]
tested and working great!

**Comment by Rdlgrmpf** [comment]
Also I now added a shortcut. This is also tested working by LordClockan

**Comment by romanbb** [comment]
got this merged manually. why does https://github.com/AOKP/vendor_aokp/commit/c0dee2a57d6f5d85a275c8959f33975d7d3ab7a6 need to be reverted? i

**Comment by LorDClockaN** [comment]
you're right, that is for InitD to be enabled by default on boot

**Pull request closed without merging**
