### PR TITLE
Missing czech translations

### PR DESCRIPTION
**Pull request by kecinzer**
Merge it please.

### CODE REVIEW

**Comment by sethyx** [comment]
please use our gerrit if you want to contribute:
http://rootzwiki.com/topic/22424-aokp-gerrit-tutorial/

**Comment by kecinzer** [comment]
Why you start use gerrit?

**Comment by sethyx** [comment]
Mainly to avoid conflicts and to help each others work by reviewing/verifying commits.
And because it's cool!

**Comment by kecinzer** [comment]
Ok, but it's more work for me to teach another system.
So, Github repo will be closed or how it works?

**Comment by sethyx** [comment]
No, we're still using github, but every change has to go through gerrit. Think of it as a review system.
If somebody pushes something to gerrit, the team can approve/patch it before merging on a clear interface.
If a commit gets approved, gerrit will push it to github automatically.

**Comment by kecinzer** [comment]
Ok, thank you for explanation. But I'm on Windows and don't know, how to make work command "repo". I think I have to use my Ubuntu in VMWare.

**Pull request closed without merging**
